name: Sync to Hugging Face
on:
  push:
    branches: [main, master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git push --force https://${HF_TOKEN}@huggingface.co/spaces/blaze-73/parapharmacy-api main
