name: Sync to Hugging Face
on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # We use a specific git command to push to HF
          git remote add hf https://${HF_TOKEN}@huggingface.co/spaces/blaze-73/parapharmacy-api
          git push --force hf main
